Traceback (most recent call last):
  File "03_errorExample_v2.py", line 6, in <module>
    raise Exception('This is the erro message')
Exception: This is the erro message
